# Generated by Django 2.0.1 on 2018-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotatorlink',
            old_name='times_viewd',
            new_name='times_view',
        ),
        migrations.AddField(
            model_name='rotator',
            name='rotator_slug',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rotatorlink',
            name='rotator_link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
