# Generated by Django 2.0.1 on 2018-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0002_auto_20180115_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatorlink',
            name='discord_user_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
