# Generated by Django 2.0.1 on 2018-01-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0004_rotator_current_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotatorlink',
            old_name='times_view',
            new_name='times_viewed',
        ),
    ]
